version: '2'
services:

  consul:
    restart: always
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  registrator:
    restart: always
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

  requisition-refui:
    image: openlmis/requisition-refui:3.0.0-beta
    env_file: .env
    environment:
      # Changing the virtual location affects loading of the assets on UI. Handle with care.
      - VIRTUAL_LOCATION=public

  requisition:
    restart: always
    image: openlmis/requisition:3.0.0-beta
    env_file: .env
    environment:
      VIRTUAL_LOCATION: requisition
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=file:///demo-data/data.sql'
    depends_on: [log]

  referencedata:
    restart: always
    image: openlmis/referencedata:3.0.0-beta
    env_file: .env
    environment:
      VIRTUAL_LOCATION: referencedata
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=file:///demo-data/data.sql'
    depends_on: [log]

  auth:
    restart: always
    image: openlmis/auth:3.0.0-beta
    env_file: .env
    environment:
      VIRTUAL_LOCATION: auth
      JAVA_OPTS: '-Dspring.jpa.properties.hibernate.hbm2ddl.import_files=file:///demo-data/data.sql'
    depends_on: [log]

  notification:
    restart: always
    image: openlmis/notification:3.0.0-beta
    env_file: .env
    environment:
      VIRTUAL_LOCATION: notification
    depends_on: [log]

  db:
    restart: always
    image: openlmis/postgres
    env_file: .env
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:514"
        syslog-facility: "local1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    depends_on: [log]

  log:
    restart: always
    image: openlmis/rsyslog
    volumes:
      - rsyslog:/var/log
    ports:
      - "514:514"

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  pgdata:
    external: false
  rsyslog:
    external: false
